normalize_responses_params must return an array
So it turns out that we cannot just return `params[:responses]` if it is
anything but an array as the calling method will fail:

```
 Failure/Error:
              responses.inject(start_state) do |state, response|
                return state if state.error

                transistion_state(state, response)
              end

      ActionView::Template::Error:
        undefined method `inject' for #<ActionController::Parameters:0x00005576d7ad2840>
        Did you mean?  inspect
      # ./lib/smart_answer/flow.rb:133:in `process'
      # ./lib/smart_answer/flow.rb:172:in `path'
      # ./app/presenters/flow_presenter.rb:50:in `collapsed_questions'
```

Instead we have to make sure that an array is always returned.
This call into question the need for `Hash`, as it is more than likely
that this should be caught by `ActionController::Parameters`